/* this file was generated by vite-svg-sprite-wrapper */
export type SvgIconId = 'ellipseMock' | 'logo--white' | 'logo_full' | 'swiper-next-btn' | 'swiper-next-btn--hover' | 'swiper-prev-btn' | 'swiper-prev-btn--hover' | 'telegram' | 'vk'
