/* this file was generated by vite-svg-sprite-wrapper */
export type SvgIconId = 'ellipseMock' | 'logo--black' | 'logo--white' | 'logo_full' | 'menu--close' | 'menu--open' | 'swiper-arrow-btn' | 'telegram' | 'vk'
